#!/usr/bin/env python3
"""Generate updated specialty_config.json from new taxonomy document.
Preserves all existing IDs for backward compatibility."""

import json
import re

def make_id(text):
    """Convert label to snake_case ID"""
    s = text.lower().strip()
    s = s.replace('&', 'and').replace('/', '_')
    s = re.sub(r'[^a-z0-9]+', '_', s)
    s = s.strip('_')
    return s

# New taxonomy from document
NEW_TAXONOMY = [
    {
        "label": "Allergy and Immunology",
        "subspecialties": [
            {"label": "General/Core", "topics": "Anaphylaxis Management; Asthma Phenotyping (Th2 high/low); Primary Immunodeficiencies (CVID/SCID); Food Allergy & OIT; Atopic Dermatitis; Hereditary Angioedema; Drug Desensitization (AERD); Eosinophilic Esophagitis; Allergic Rhinitis Immunotherapy; Chronic Spontaneous Urticaria; Contact Dermatitis (Patch testing); Insect Venom Hypersensitivity; Mastocytosis; Occupational Asthma; Hypereosinophilic Syndromes", "journals": "J Allergy Clin Immunol; Allergy; Lancet Respir Med; J Immunol; Pediatr Allergy Immunol; Clin Exp Allergy; Ann Allergy Asthma Immunol; Curr Opin Allergy Clin Immunol; JACI: In Practice; Immunity"},
        ]
    },
    {
        "label": "Anesthesiology",
        "subspecialties": [
            {"label": "General/Core", "topics": "Airway Management Algorithms; Inhalational Anesthetics Pharmacology; Neuromuscular Blockade & Reversal; Neuraxial Anesthesia (Spinal/Epidural); Malignant Hyperthermia Protocols; Hemodynamic Monitoring (TEE/Arterial); Massive Transfusion Protocols; Preoperative Cardiac Risk Stratification; Pediatric Anesthesia Basics; Obstetric Anesthesia (Preeclampsia/Labor); Local Anesthetic Toxicity (LAST); Post-Anesthesia Care (PACU); Ambulatory Anesthesia Criteria; Regional Nerve Blocks; Intravenous Anesthetics (Propofol/Ketamine)", "journals": "Anesthesiology; Br J Anaesth; Anaesthesia; Anesth Analg; Pain; Reg Anesth Pain Med; Eur J Anaesthesiol; Can J Anaesth; Acta Anaesthesiol Scand; Curr Opin Anaesthesiol"},
            {"label": "Critical Care Medicine", "topics": "Sepsis Resuscitation Bundles; ARDS Ventilation Strategies (Prone/Low TV); Shock State Differentiation; Renal Replacement Therapy (CRRT); ICP Monitoring & Management; Trauma Resuscitation; Nutritional Support in ICU; Delirium Management (ABCDEF Bundle); Ventilator-Associated Pneumonia; Coagulopathy Management; Post-Cardiac Arrest TTM; Brain Death Determination; End-of-Life Care; ICU Toxicology; Mechanical Circulatory Support and ECMO", "journals": "Am J Respir Crit Care Med; Crit Care Med; Intensive Care Med; Lancet Respir Med; Chest; J Trauma Acute Care Surg; Shock; Critical Care; Ann Intensive Care; ASAIO J"},
            {"label": "Pain Medicine", "topics": "Spinal Cord Stimulation; Complex Regional Pain Syndrome (CRPS); Radiofrequency Ablation; Opioid Stewardship & Risk Mitigation; Neuropathic Pain Pharmacotherapy; Cancer Pain Management (WHO Ladder); Epidural Steroid Injections; Sympathetic Nerve Blocks; Myofascial Pain Syndrome; Headache/Migraine Interventions; Vertebroplasty/Kyphoplasty; Sacroiliac Joint Dysfunction; Discogenic Pain; Psychology of Pain (CBT); Regenerative Medicine Injections", "journals": "PAIN; Reg Anesth Pain Med; J Pain; Pain Med; Eur J Pain; Clin J Pain; Pain Physician; Anaesth Crit Care Pain Med; J Pain Symptom Manage; Molecular Pain"},
        ]
    },
    {
        "label": "Cardiac Surgery",
        "subspecialties": [
            {"label": "General Cardiac Surgery", "topics": "Coronary Artery Bypass Grafting (On/Off Pump); Mitral Valve Repair/Replacement; Aortic Valve Replacement (Surgical); Tricuspid Valve Surgery; Atrial Fibrillation Ablation (Maze); Pericardiectomy; Cardiac Tumors (Myxoma); Septal Myectomy; Post-Infarction VSD Repair; LV Aneurysm Repair; Minimally Invasive Valve Surgery; Reoperative Cardiac Surgery; Sternotomy Infection Management; Cardiopulmonary Bypass Management; Myocardial Protection (Cardioplegia)", "journals": "J Thorac Cardiovasc Surg; Ann Thorac Surg; Eur J Cardiothorac Surg; J Card Surg; Ann Cardiothorac Surg; Innovations; Semin Thorac Cardiovasc Surg; Oper Tech Thorac Cardiovasc Surg; Asian Cardiovasc Thorac Ann; Heart Surg Forum"},
            {"label": "Congenital Diseases", "topics": "Transposition of Great Arteries Repair; Tetralogy of Fallot Repair; Hypoplastic Left Heart Syndrome (Norwood/Fontan); Atrioventricular Septal Defect Repair; Total Anomalous Pulmonary Venous Return; Coarctation of the Aorta Repair; Ebstein Anomaly (Cone Procedure); Truncus Arteriosus Repair; VSD/ASD Closure Techniques; Pulmonary Atresia Management; ROSS Procedure; Arterial Switch Operation; Congenital Mitral Valve Repair; Hybrid Procedures; Adult Congenital Heart Disease Surgery", "journals": "World J Pediatr Congenit Heart Surg; Cardiol Young; Congenit Heart Dis; Pediatr Cardiol; J Thorac Cardiovasc Surg; Ann Thorac Surg; Eur J Cardiothorac Surg; Semin Thorac Cardiovasc Surg; Oper Tech Thorac Cardiovasc Surg; JACC: Advances"},
            {"label": "Aortic Surgery", "topics": "Aortic Root Replacement (Bentall); Valve-Sparing Root Replacement (David/Yacoub); Ascending Aorta Replacement; Hemiarch/Total Arch Replacement; Frozen Elephant Trunk Technique; TEVAR (Thoracic Endovascular Aortic Repair); Type A Dissection Repair; Type B Dissection Management; Thoracoabdominal Aneurysm Repair; Connective Tissue Disorders (Marfan/Loeys-Dietz); Deep Hypothermic Circulatory Arrest; Cerebral Protection Strategies; Aortic Valve Repair; Hybrid Aortic Arch Repair; Infected Aortic Graft Management", "journals": "Ann Cardiothorac Surg; AORTA; J Thorac Cardiovasc Surg; Ann Thorac Surg; Eur J Cardiothorac Surg; J Endovasc Ther; J Card Surg; Innovations; Semin Thorac Cardiovasc Surg; Interact Cardiovasc Thorac Surg"},
            {"label": "Mechanical Circulatory Support/ECMO", "topics": "VA-ECMO Cannulation & Management; VV-ECMO Principles; Impella Insertion & Management; Intra-Aortic Balloon Pump; Left Ventricular Assist Devices (LVADs - HeartMate 3); Right Ventricular Assist Devices; Total Artificial Heart; ECMO for Cardiogenic Shock; ECMO for Respiratory Failure; Anticoagulation for MCS; Bridge to Transplant vs Destination Therapy; Device Thrombosis & Hemolysis; Right Heart Failure Management in LVAD; Driveline Infection; Weaning from MCS", "journals": "ASAIO J; J Heart Lung Transplant; Artif Organs; Perfusion; Int J Artif Organs; Ann Thorac Surg; J Thorac Cardiovasc Surg; Eur J Heart Fail; Crit Care Med; Circ Heart Fail"},
        ]
    },
    {
        "label": "Cardiology",
        "subspecialties": [
            {"label": "General Cardiology", "topics": "Acute Coronary Syndromes (STEMI/NSTEMI); Stable Ischemic Heart Disease; Heart Failure Management (GDMT); Atrial Fibrillation Management; Valvular Heart Disease Assessment; Hypertension Guidelines; Dyslipidemia Management; Preoperative Cardiac Risk Assessment; Pericarditis & Effusion; Infective Endocarditis; Adult Congenital Heart Disease Basics; Cardio-Oncology; Cardiac Amyloidosis; Syncope Evaluation; Primary/Secondary Prevention", "journals": "J Am Coll Cardiol; Circulation; Eur Heart J; JAMA Cardiol; Nat Rev Cardiol; Heart; Am J Cardiol; Clin Cardiol; Int J Cardiol; Eur J Prev Cardiol"},
            {"label": "Advanced Echocardiography", "topics": "Transthoracic Echo (TTE) Quantitation; Transesophageal Echo (TEE) Protocols; 3D Echocardiography; Speckle Tracking & Strain Imaging; Diastolic Function Assessment; Stress Echocardiography; Prosthetic Valve Assessment; Interventional Echo (TAVR/MitraClip guidance); Right Ventricular Function; Congenital Echo; Contrast Echocardiography; Intraoperative TEE; Pericardial Disease Imaging; Cardio-Oncology Imaging; Echo in Shock/Hemodynamics", "journals": "J Am Soc Echocardiogr; Eur Heart J Cardiovasc Imaging; JACC Cardiovasc Imaging; Circ Cardiovasc Imaging; J Echocardiogr; Echocardiography; CASE; Ultrasound Med Biol; Clin Res Cardiol; Int J Cardiovasc Imaging"},
            {"label": "Electrophysiology", "topics": "Atrial Fibrillation Ablation (PVI); SVT Ablation; Ventricular Tachycardia Ablation; Pacemaker Implantation; ICD Implantation; CRT (Resynchronization) Therapy; Lead Extraction; Channelopathies (Long QT/Brugada); Syncope & Tilt Table; Anticoagulation for Arrhythmias; Left Atrial Appendage Closure (Watchman); His Bundle/Left Bundle Pacing; Sudden Cardiac Death Risk Stratification; Intracardiac Echocardiography; Mapping Systems (3D)", "journals": "Heart Rhythm; JACC Clin Electrophysiol; Circ Arrhythm Electrophysiol; Europace; J Cardiovasc Electrophysiol; Pacing Clin Electrophysiol; Heart Rhythm O2; EP Europace; Arrhythm Electrophysiol Rev; J Interv Card Electrophysiol"},
            {"label": "Interventional Cardiology", "topics": "PCI (Percutaneous Coronary Intervention); STEMI Management/Primary PCI; Complex High-Risk Indicated Procedures (CHIP); CTO (Chronic Total Occlusion) Techniques; Intravascular Imaging (IVUS/OCT); Coronary Physiology (FFR/iFR); Cardiogenic Shock (Impella/Balloon Pump); Access Site Management (Radial vs Femoral); Antiplatelet Therapy (DAPT); Stent Thrombosis/Restenosis; Rotational/Orbital Atherectomy; Bypass Graft Interventions; Complication Management (Perforation/Dissection); Peripheral Intervention Basics; Structural Basics", "journals": "JACC Cardiovasc Interv; Circ Cardiovasc Interv; EuroIntervention; Catheter Cardiovasc Interv; JSCAI; J Interv Cardiol; Coron Artery Dis; Struct Heart; Cardiovasc Revasc Med; PCR E-Journal"},
            {"label": "Structural Cardiology", "topics": "TAVR (Transcatheter Aortic Valve Replacement); MitraClip (TEER); TMVR (Mitral Replacement); Tricuspid Valve Interventions (TriClip); Left Atrial Appendage Occlusion; ASD/PFO Closure; Paravalvular Leak Closure; Alcohol Septal Ablation; Valve-in-Valve Procedures; CT Planning for Structural Heart; Large Bore Access & Closure; Cerebral Embolic Protection; Transseptal Puncture Techniques; VSD Closure (Post-MI/Congenital); Pulmonary Valve Implantation (Melody/Sapien)", "journals": "EuroIntervention; JACC Cardiovasc Interv; Struct Heart; Circ Cardiovasc Interv; Catheter Cardiovasc Interv; Ann Cardiothorac Surg; J Struct Heart Dis; Front Cardiovasc Med; Interv Cardiol Rev; JACC: Case Reports"},
            {"label": "Advanced Heart Failure", "topics": "Heart Transplant Listing Criteria/Evaluation; LVAD Patient Management; Right Heart Catheterization Hemodynamics; Immunosuppression Protocols; Rejection Surveillance (Biopsy); Cardiorenal Syndrome; Infiltrative Cardiomyopathies (Amyloid/Sarcoid); Pulmonary Hypertension (Group 1 vs 2); Cardiogenic Shock Classifications (SCAI); Inotropes & Vasopressors; Temporary MCS (Impella/ECMO); End-of-Life/Palliative Care in HF; Genetic Cardiomyopathies; HFpEF Management; Donor Selection/Management", "journals": "J Heart Lung Transplant; JACC Heart Fail; Circ Heart Fail; Eur J Heart Fail; J Card Fail; ESC Heart Fail; Heart Fail Rev; Transplantation; ASAIO J; Clin Transplant"},
        ]
    },
    {"label": "Colon and Rectal Surgery", "subspecialties": [{"label": "General/Core", "topics": "Rectal Cancer (TME/Neoadjuvant); Diverticulitis (Hinchey/Hartman's); Inflammatory Bowel Disease Surgery; Anal Fistula (LIFT/Seton); Hemorrhoids (Banding/Hemorrhoidectomy); Anal Fissure (LIS); Fecal Incontinence (SNS); Colon Cancer Screening/Polypectomy; Rectal Prolapse Repair; Anal Squamous Cell Carcinoma (Nigro); Pilonidal Disease (Flaps); Lynch Syndrome/FAP Management; Lower GI Bleeding Localization; Stoma Creation & Complications; Pelvic Floor Disorders", "journals": "Dis Colon Rectum; Colorectal Dis; Ann Surg; Br J Surg; Int J Colorectal Dis; Tech Coloproctol; Gastroenterology; Lancet Oncol; J Gastrointest Surg; Surg Endosc"}]},
    {"label": "Dermatology", "subspecialties": [
        {"label": "General/Core", "topics": "Melanoma Staging & Management; Psoriasis (Biologics/Pathophysiology); Atopic Dermatitis (JAK inhibitors); Basal Cell Carcinoma; Acne Vulgaris (Isotretinoin); Autoimmune Blistering Diseases; Cutaneous Lymphoma (MF/SS); Severe Drug Eruptions (SJS/DRESS); Hidradenitis Suppurativa; Cutaneous Lupus & Connective Tissue Disease; Vitiligo & Pigmentary Disorders; Nail Disorders; Alopecia (Scarring vs Non-scarring); Cutaneous Infections; Dermoscopy Patterns", "journals": "J Am Acad Dermatol; JAMA Dermatol; J Invest Dermatol; Br J Dermatol; J Eur Acad Dermatol Venereol; Am J Clin Dermatol; Dermatol Surg; Contact Dermatitis; Acta Derm Venereol; Exp Dermatol"},
        {"label": "Dermatopathology", "topics": "Melanocytic Neoplasms (Nevus vs Melanoma); Interface Dermatitis Patterns; Spitzoid Tumors; Psoriasiform Dermatitis; Vesiculobullous Disease Histology; Cutaneous Lymphoma Immunophenotyping; Adnexal Tumor Diagnosis; Soft Tissue Tumors (DFSP/Vascular); Panniculitis Patterns; Granulomatous Inflammation; Alopecia Histology; Vasculitis Classification; Infectious Agent Identification; Metastatic Carcinoma IHC; Genodermatoses Histology", "journals": "J Cutan Pathol; Am J Dermatopathol; Histopathology; Modern Pathol; Arch Pathol Lab Med; Semin Diagn Pathol; Hum Pathol; Virchows Arch; Dermatopathology; Appl Immunohistochem Mol Morphol"},
        {"label": "Micrographic Surgery & Oncology", "topics": "Mohs Appropriate Use Criteria (AUC); Flap Reconstruction Biomechanics; Grafting Techniques; Basal Cell Carcinoma Histology; Squamous Cell Carcinoma Staging; Melanoma Margin Control (Slow Mohs); Rare Tumor Management (DFSP); Nail Unit Surgery; Facial Anatomy & Danger Zones; Surgical Complications (Hematoma/Necrosis); Anticoagulation Management; Scar Revision Techniques; Tumescent Anesthesia; Cartilage Grafting; Multidisciplinary Oncology Care", "journals": "Dermatol Surg; J Am Acad Dermatol; JAMA Dermatol; Plast Reconstr Surg; JAMA Facial Plast Surg; J Surg Oncol; Head Neck; Ann Surg Oncol; J Cutan Pathol; Ophthalmic Plast Reconstr Surg"},
    ]},
    {"label": "Emergency Medicine", "subspecialties": [
        {"label": "General/Core", "topics": "Acute Coronary Syndromes; Stroke Code Management (tPA/Thrombectomy); Sepsis Resuscitation; Trauma (ATLS/E-FAST); Airway Management (RSI); Acute Respiratory Failure; Pediatric Resuscitation (PALS); Toxicology & Overdose; Acute Abdominal Pain Workup; Traumatic Brain Injury; Psychiatric Emergencies; Orthopedic Reductions; Environmental Emergencies (Heat/Cold/Burns); Point-of-Care Ultrasound (POCUS); Disaster/Mass Casualty Triage", "journals": "Ann Emerg Med; Resuscitation; Acad Emerg Med; Am J Emerg Med; Emerg Med J; J Emerg Med; Scand J Trauma Resusc Emerg Med; Prehosp Emerg Care; Intern Emerg Med; Pediatr Emerg Care"},
        {"label": "Medical Toxicology", "topics": "Acetaminophen Toxicity (Rumack-Matthew); Toxic Alcohols (Osmolar Gap); Opioid Toxicity & Withdrawal; Cardioactive Steroid Toxicity; Beta-Blocker/CCB Overdose (HDI); Sedative-Hypnotic Withdrawal; Serotonin Syndrome vs NMS; Envenomations (Snake/Spider); Heavy Metal Poisoning; Cellular Asphyxiants (CO/CN); Caustic Ingestions; Antidepressant Toxicity (TCA/Bupropion); Salicylate Toxicity; Occupational Toxicology; Pediatric Ingestions", "journals": "Clin Toxicol; J Med Toxicol; Toxicol Sci; Toxicology; Crit Rev Toxicol; Neurotoxicology; Ther Drug Monit; Hum Exp Toxicol; Arch Toxicol; Food Chem Toxicol"},
    ]},
    {"label": "Family Medicine", "subspecialties": [{"label": "General/Core", "topics": "Hypertension Management; Type 2 Diabetes & Complications; USPSTF Preventive Screening; Musculoskeletal Pain (Back/Joint); Mental Health (Depression/Anxiety); Respiratory Infections (URI/Pneumonia); Asthma/COPD Management; Well-Child Care & Vaccinations; Women's Health (Contraception/Prenatal); Geriatric Care (Dementia/Falls); Lipid Management (ASCVD Risk); Thyroid Disorders; Common Dermatoses; Substance Use Disorders; Social Determinants of Health", "journals": "Ann Fam Med; Am Fam Physician; Br J Gen Pract; J Am Board Fam Med; Fam Med; BMC Prim Care; Fam Pract; J Prim Care Community Health; Can Fam Physician; Prim Care"}]},
    {"label": "Internal Medicine", "subspecialties": [
        {"label": "General/Core", "topics": "Hospital Medicine (CHF/Sepsis); Venous Thromboembolism (DVT/PE); Acute Kidney Injury Workup; Hypertension (Inpatient/Outpatient); Diabetes Mellitus (DKA/HHS); Liver Disease/Cirrhosis; Infectious Disease (Pneumonia/UTI); Anemia Evaluation; Electrolyte Disorders; Perioperative Medicine; COPD/Asthma Exacerbations; Delirium & Dementia; Adult Preventive Medicine; Rheumatologic Screening; Palliative Care Basics", "journals": "N Engl J Med; Lancet; JAMA; BMJ; Ann Intern Med; JAMA Intern Med; J Intern Med; Mayo Clin Proc; Am J Med; Lancet Reg Health"},
        {"label": "Critical Care Medicine", "topics": "Sepsis & Septic Shock (Surviving Sepsis); ARDS & Mechanical Ventilation Strategies; Multiorgan Failure & MODS; Hemodynamic Monitoring (PAC/POCUS); Vasoactive Support (Shock Management); Acute Kidney Injury & RRT; Post-Cardiac Arrest Care (TTM); ICU Delirium & Sedation (PADIS); GI Hemorrhage & Massive Transfusion; Acid-Base & Electrolyte Emergencies; Toxicology & Withdrawal; Severe Pneumonia (CAP/HAP/VAP); End-of-Life Care & Ethics; Pulmonary Embolism & DVT; Mechanical Circulatory Support and ECMO", "journals": "Am J Respir Crit Care Med; Crit Care Med; Intensive Care Med; Lancet Respir Med; Chest; JAMA; N Engl J Med; Ann Intensive Care; J Crit Care; ASAIO J"},
        {"label": "Endocrinology, Diabetes & Metabolism", "topics": "Diabetes (Type 1 & 2 Management); Thyroid Nodules & Cancer; Adrenal Disorders (Cushing's/Addison's); Pituitary Disorders (Adenomas); Calcium & Parathyroid Disorders; Osteoporosis Management; Hypogonadism & Reproductive Endo; Obesity Medicine; Lipid Disorders; Hypertension (Endocrine Causes); Transgender Hormone Therapy; Hypoglycemia Disorders; MEN Syndromes; Neuroendocrine Tumors; Metabolic Bone Disease", "journals": "Lancet Diabetes Endocrinol; Diabetes Care; J Clin Endocrinol Metab; Nat Rev Endocrinol; Endocr Rev; Diabetes; Diabetologia; Thyroid; J Bone Miner Res; Eur J Endocrinol"},
        {"label": "Gastroenterology", "topics": "GI Bleeding Management; Colorectal Cancer Screening; Inflammatory Bowel Disease; Cirrhosis & Complications; GERD & Barrett's Esophagus; Pancreatitis (Acute/Chronic); Viral Hepatitis (B/C); MASLD/NAFLD; Biliary Tract Disease; Functional GI Disorders (IBS); Dysphagia & Motility; Malabsorption Syndromes; C. difficile Infection; GI Oncology Staging; Nutrition (Enteral/Parenteral)", "journals": "Gastroenterology; Gut; J Hepatol; Hepatology; Lancet Gastroenterol Hepatol; Am J Gastroenterol; Clin Gastroenterol Hepatol; Nat Rev Gastroenterol Hepatol; Endoscopy; Gastrointest Endosc"},
        {"label": "Hematology", "topics": "Anemia Differential Diagnosis; Acute Leukemias (AML/ALL); Chronic Leukemias (CLL/CML); Lymphomas (Hodgkin/Non-Hodgkin); Plasma Cell Dyscrasias (Myeloma); Myeloproliferative Neoplasms; Coagulation Disorders (Hemophilia/VWD); Thrombosis & Thrombophilia; Platelet Disorders (ITP/TTP); Bone Marrow Failure Syndromes; Hematopoietic Stem Cell Transplant; Transfusion Medicine; Sickle Cell Disease; Heme-Onc Emergencies; Iron Overload/Deficiency", "journals": "Blood; Lancet Haematol; J Clin Oncol; Leukemia; Am J Hematol; Haematologica; Br J Haematol; Blood Adv; J Thromb Haemost; Stem Cells"},
        {"label": "Infectious Disease", "topics": "HIV/AIDS Management; Antimicrobial Stewardship; Sepsis & Bloodstream Infections; Pneumonia (CAP/HAP/VAP); Endocarditis & Intravascular Infections; Skin & Soft Tissue Infections; CNS Infections (Meningitis); Intra-abdominal Infections; Sexually Transmitted Infections; Tuberculosis & Mycobacteria; Fungal Infections; Viral Hepatitis; Zoonoses & Vector-borne Diseases; Infection Control & Epidemiology; Travel Medicine", "journals": "Lancet Infect Dis; Clin Infect Dis; J Infect Dis; Emerging Infect Dis; AIDS; J Antimicrob Chemother; Antimicrob Agents Chemother; Clin Microbiol Infect; Open Forum Infect Dis; Infect Control Hosp Epidemiol"},
        {"label": "Medical Oncology", "topics": "Breast Cancer Management; Lung Cancer (NSCLC/SCLC); Colorectal Cancer; Prostate & GU Cancers; Gynecologic Malignancies; Melanoma & Skin Cancers; Sarcomas; Head & Neck Cancer; CNS Tumors; Cancer Immunotherapy Principles; Targeted Therapies & Genomics; Oncologic Emergencies; Cancer Pain & Palliative Care; Survivorship Care; Clinical Trial Design", "journals": "J Clin Oncol; Lancet Oncol; JAMA Oncol; Cancer Cell; Cancer Discov; Clin Cancer Res; Ann Oncol; Nat Rev Clin Oncol; J Natl Cancer Inst; CA Cancer J Clin"},
        {"label": "Nephrology", "topics": "Acute Kidney Injury (AKI); Chronic Kidney Disease (CKD) Stages; Glomerulonephritis; Diabetic Nephropathy; Hypertension & Renovascular Disease; Electrolyte & Acid-Base Disorders; Hemodialysis Principles; Peritoneal Dialysis; Kidney Transplantation Management; Nephrolithiasis (Stones); Cystic Kidney Diseases; Tubulointerstitial Diseases; Onco-Nephrology; Critical Care Nephrology; Drug Dosing in Renal Failure", "journals": "Kidney Int; J Am Soc Nephrol; Nat Rev Nephrol; Clin J Am Soc Nephrol; Am J Kidney Dis; Nephrol Dial Transplant; Kidney Int Rep; Semin Nephrol; Curr Opin Nephrol Hypertens; Adv Chronic Kidney Dis"},
        {"label": "Pulmonary Disease", "topics": "COPD & Emphysema; Asthma; Interstitial Lung Disease (IPF); Pulmonary Hypertension; Lung Cancer Diagnosis/Staging; Pleural Diseases; Pulmonary Infections; Cystic Fibrosis (Adult); Sleep-Disordered Breathing; Occupational Lung Disease; Sarcoidosis; Pulmonary Embolism; Critical Care Pulmonology; Interventional Pulmonology; Lung Transplantation Evaluation; Mechanical Circulatory Support and ECMO", "journals": "Am J Respir Crit Care Med; Lancet Respir Med; Chest; Eur Respir J; Thorax; Am J Respir Cell Mol Biol; J Heart Lung Transplant; Eur Respir Rev; Respirology; Ann Am Thorac Soc"},
        {"label": "Rheumatology", "topics": "Rheumatoid Arthritis; Systemic Lupus Erythematosus; Spondyloarthropathies; Crystal Arthropathies (Gout); Vasculitis Syndromes; Scleroderma/Systemic Sclerosis; Myositis; Sjogren's Syndrome; Osteoarthritis; Osteoporosis; Psoriatic Arthritis; Pediatric Rheumatology (Adult Transition); Soft Tissue Rheumatism; Autoimmune Labs/Serology; Biologic Therapy Management", "journals": "Ann Rheum Dis; Arthritis Rheumatol; Nat Rev Rheumatol; Lancet Rheumatol; Rheumatology; Arthritis Care Res; Semin Arthritis Rheum; Curr Opin Rheumatol; J Rheumatol; RMD Open"},
    ]},
    {"label": "Medical Genetics", "subspecialties": [{"label": "General/Core", "topics": "Chromosomal Aneuploidy; Inborn Errors of Metabolism; Cancer Susceptibility Syndromes; Newborn Screening; Dysmorphology & Syndromology; Neurogenetics; Connective Tissue Disorders; Prenatal Genetics; Mitochondrial Disease; Skeletal Dysplasias; Cardiogenetics; Exome/Genome Sequencing; Pharmacogenomics; Imprinting Disorders; Gene Therapy Principles", "journals": "Nat Genet; Am J Hum Genet; Genet Med; J Med Genet; Hum Mol Genet; Nat Rev Genet; PLOS Genet; Eur J Hum Genet; Hum Genet; Clin Genet"}]},
    {"label": "Neurological Surgery", "subspecialties": [{"label": "General/Core", "topics": "Brain Tumor Resection; Traumatic Brain Injury (TBI); Spine Trauma Stabilization; Degenerative Spine Disease; Cerebrovascular Surgery (Aneurysms); Hydrocephalus Management; Functional Neurosurgery (DBS); Pediatric Neurosurgery; Peripheral Nerve Surgery; Spinal Tumor Resection; Trigeminal Neuralgia; Pituitary Tumor Resection; CNS Infection Management; Pain Surgery; Neurocritical Care", "journals": "J Neurosurg; Neurosurgery; J Neurotrauma; J Neurosurg Spine; J Neurosurg Pediatr; World Neurosurg; Acta Neurochir; J Neurooncol; Spine; Oper Neurosurg"}]},
    {"label": "Neurology", "subspecialties": [
        {"label": "General/Core", "topics": "Acute Ischemic Stroke and TIA; Epilepsy and First Seizure Workup; Headache Disorders (Migraine/Cluster); Parkinson Disease and Tremor; Dementia and Cognitive Disorders; Multiple Sclerosis and Demyelinating Disease; Peripheral Neuropathy; Myasthenia Gravis and Neuromuscular Junction Disease; Autoimmune Encephalitis; Functional Neurological Disorder; Neurogenetics; Sleep-Neurology Interface; Neurodiagnostics (EEG/EMG/MRI/CSF); Neurocritical Care Emergencies; Neurologic Complications of Systemic Disease", "journals": "Lancet Neurol; Neurology; JAMA Neurol; Brain; Ann Neurol; Nat Rev Neurol; J Neurol Neurosurg Psychiatry; Neurol Neuroimmunol Neuroinflamm; Neurotherapeutics; Neurology: Clinical Practice"},
        {"label": "Vascular Neurology", "topics": "Acute Reperfusion for Ischemic Stroke; Intracerebral Hemorrhage Management; Subarachnoid Hemorrhage and Vasospasm; Secondary Stroke Prevention; Cerebral Venous Sinus Thrombosis; Carotid and Intracranial Atherosclerosis; Cervical Artery Dissection; Cryptogenic Stroke and PFO; Small Vessel Disease and Lacunar Stroke; Stroke in the Young; Cerebral Amyloid Angiopathy; Neurovascular Imaging and Perfusion; Telestroke and Systems of Care; Post-Stroke Seizures and Complications; Stroke Recovery and Rehabilitation", "journals": "Stroke; Int J Stroke; Lancet Neurol; JAMA Neurol; Neurology; Ann Neurol; Brain; Neurology: Clinical Practice; Circulation; Front Neurol"},
        {"label": "Epilepsy", "topics": "First Seizure Evaluation; Focal versus Generalized Epilepsy Classification; Status Epilepticus; Drug-Resistant Epilepsy; Antiseizure Medication Selection and Monitoring; Video-EEG Monitoring; Psychogenic Nonepileptic Seizures; Epilepsy Surgery Evaluation; Neuromodulation (VNS/RNS/DBS); Autoimmune and Inflammatory Epilepsy; Women with Epilepsy and Pregnancy; SUDEP Risk Reduction; Genetic Epilepsies; Comorbid Mood and Cognitive Disorders; Driving, Safety, and Counseling", "journals": "Epilepsia; Epilepsy Behav; Seizure; Epilepsia Open; Neurology; JAMA Neurol; Ann Neurol; Lancet Neurol; Clin Neurophysiol; Epileptic Disord"},
        {"label": "Movement Disorders", "topics": "Parkinson Disease Diagnosis and Progression; Levodopa Complications and Motor Fluctuations; Atypical Parkinsonism (PSP/MSA/CBD); Essential Tremor; Dystonia; Huntington Disease; Tourette Syndrome and Tic Disorders; Ataxias; Deep Brain Stimulation; Botulinum Toxin Therapy; Functional Movement Disorders; Wilson Disease; Drug-Induced Movement Disorders; Gait, Balance, and Falls; Autonomic Dysfunction in Synucleinopathy", "journals": "Mov Disord; Parkinsonism Relat Disord; Tremor Other Hyperkinet Mov (N Y); Neurology; JAMA Neurol; Brain; Ann Neurol; Lancet Neurol; Clin Neuropharmacol; npj Parkinsons Dis"},
        {"label": "Neuromuscular Medicine", "topics": "Peripheral Neuropathy Evaluation; Guillain-Barre Syndrome; Chronic Inflammatory Demyelinating Polyneuropathy; Amyotrophic Lateral Sclerosis; Myasthenia Gravis; Muscular Dystrophies; Inflammatory Myopathies; Metabolic and Mitochondrial Myopathies; EMG and NCS for Weakness; Hereditary Neuropathies; Respiratory Management in Neuromuscular Disease; Neuromuscular Ultrasound; Immune Therapies and Monitoring; Genetic Testing and Counseling; Dysphagia and Multidisciplinary Care", "journals": "Muscle Nerve; Neuromuscul Disord; Amyotroph Lateral Scler Frontotemporal Degener; J Peripher Nerv Syst; Neurology; JAMA Neurol; Ann Neurol; Brain; Clin Neurophysiol; J Neurol Neurosurg Psychiatry"},
        {"label": "Neuroimmunology and Demyelinating Disease", "topics": "Multiple Sclerosis Phenotypes; Disease-Modifying Therapy Selection; Progressive Multiple Sclerosis; Neuromyelitis Optica Spectrum Disorder; MOG Antibody Disease; Autoimmune Encephalitis; CNS Vasculitis and Neuroinflammation; MRI Surveillance and Biomarkers; CSF Oligoclonal Bands and Diagnostics; Relapse Management; Vaccination and Infection Risk on Immunotherapy; Pregnancy and Reproductive Issues; Optic Neuritis and Neuro-ophthalmic Demyelination; Fatigue and Symptom Management; Treatment Safety including PML", "journals": "Neurol Neuroimmunol Neuroinflamm; Mult Scler; Mult Scler Relat Disord; Neurology; JAMA Neurol; Ann Neurol; Brain; Lancet Neurol; J Neuroinflammation; Nat Rev Neurol"},
        {"label": "Headache Medicine", "topics": "Migraine Acute Therapy; Migraine Prevention including CGRP Therapies; Medication-Overuse Headache; Cluster Headache; Trigeminal Autonomic Cephalalgias; Status Migrainosus; Secondary Headache Red Flags; Idiopathic Intracranial Hypertension; Spontaneous Intracranial Hypotension; Cervicogenic Headache and Occipital Neuralgia; Menstrual and Hormonal Migraine; Headache in Pregnancy; Procedural and Neuromodulation Therapies; Post-traumatic Headache; Patient Education and Disability Reduction", "journals": "Headache; Cephalalgia; J Headache Pain; Neurology; JAMA Neurol; Brain; Ann Neurol; Lancet Neurol; Curr Pain Headache Rep; Neurol Sci"},
        {"label": "Sleep Neurology", "topics": "Obstructive Sleep Apnea; Central Sleep Apnea; REM Sleep Behavior Disorder; Narcolepsy and Idiopathic Hypersomnia; Restless Legs Syndrome and Periodic Limb Movement Disorder; Parasomnias; Circadian Rhythm Sleep-Wake Disorders; Insomnia in Neurologic Disease; Sleep and Epilepsy; Sleep Disorders in Neurodegeneration; Sleep Testing (PSG/HSAT) Interpretation; PAP Therapy Selection and Troubleshooting; Medication Effects on Sleep; Drowsy Driving and Safety Counseling; Integrated Behavioral and Neurologic Sleep Care", "journals": "Sleep; J Clin Sleep Med; Sleep Med Rev; Sleep Med; J Sleep Res; Neurology; Lancet Neurol; JAMA Neurol; Chest; Ann Neurol"},
        {"label": "Neurocritical Care", "topics": "Status Epilepticus; Elevated Intracranial Pressure and Herniation; Traumatic Brain Injury; Large Hemispheric Infarction; Intracerebral Hemorrhage in the ICU; Subarachnoid Hemorrhage and Vasospasm; Post-Cardiac Arrest Neuroprognostication; Continuous EEG and Neuromonitoring; Acute Neuromuscular Respiratory Failure; CNS Infection and Encephalitis in Critical Care; Osmotherapy and Sodium Disorders; Delirium and Sedation Strategies; Brain Death and Death by Neurologic Criteria; ICU Ethics and Goals of Care; Multidisciplinary Neuroresuscitation Systems", "journals": "Neurocrit Care; Crit Care Med; Intensive Care Med; Lancet Neurol; Neurology; JAMA Neurol; Ann Neurol; Stroke; Resuscitation; Crit Care Neurology"},
        {"label": "Behavioral and Cognitive Neurology", "topics": "Alzheimer Disease Biomarker-Based Diagnosis; Frontotemporal Dementia; Dementia with Lewy Bodies; Vascular Cognitive Impairment; Mild Cognitive Impairment; Delirium; Aphasia and Apraxia Syndromes; Neuropsychiatric Symptoms of Dementia; Neuropsychological Testing Integration; Autoimmune and Reversible Cognitive Syndromes; Normal Pressure Hydrocephalus; Capacity, Safety, and Driving Assessment; Caregiver Support and Behavioral Management; Risk Reduction and Dementia Prevention; Cognitive Rehabilitation and Longitudinal Care", "journals": "Alzheimers Dement; JAMA Neurol; Neurology; Lancet Neurol; Ann Neurol; Brain; J Alzheimers Dis; Neurobiol Aging; J Prev Alzheimers Dis; Neurology: Clinical Practice"},
        {"label": "Neuro-oncology", "topics": "Glioblastoma Management; Diffuse Low-Grade Glioma and Molecular Classification; Brain Metastases; Leptomeningeal Disease; Primary CNS Lymphoma; Seizure Management in Brain Tumor; Peritumoral Edema and Steroid Stewardship; Radiation Necrosis versus Tumor Progression; Tumor Treating Fields; Response Assessment and Advanced Neuroimaging; Meningioma; Spinal Cord Tumors; Cancer-Associated Neurologic Syndromes; Cognitive and Functional Survivorship; Palliative Neuro-oncology", "journals": "Neuro Oncol; Neurooncol Adv; J Clin Oncol; JAMA Oncol; Lancet Oncol; Ann Neurol; J Neurosurg; Nat Rev Clin Oncol; Cancer; Neurotherapeutics"},
        {"label": "Clinical Neurophysiology", "topics": "Routine EEG Interpretation; Continuous ICU EEG; Long-Term Video EEG Monitoring; Nerve Conduction Studies; Needle EMG; Evoked Potentials; Intraoperative Neuromonitoring; Single-Fiber EMG; Neuromuscular Ultrasound Integration; Localization in Focal Epilepsy; EEG in Encephalopathy and Coma; Neonatal and Pediatric EEG Fundamentals; Quantitative EEG Applications; Functional Cortical Mapping; Quality and Safety in Electrodiagnostics", "journals": "Clin Neurophysiol; Clin Neurophysiol Pract; J Clin Neurophysiol; Neurology; Epilepsia; Muscle Nerve; Ann Neurol; JAMA Neurol; Brain; Seizure"},
    ]},
    {"label": "Nuclear Medicine", "subspecialties": [{"label": "General/Core", "topics": "PET/CT Oncology Imaging; Myocardial Perfusion Imaging; Ventilation/Perfusion (V/Q) Scans; Thyroid Disease Therapy (I-131); Bone Scintigraphy; Renal Scintigraphy; Gastric Emptying Studies; Infection/Inflammation Imaging; Sentinel Lymph Node Mapping; Radiopharmaceutical Safety/Physics; Neuro-PET (Dementia); Parathyroid Imaging; Theranostics (Lu-177); Pediatric Nuclear Medicine; Radiation Safety Regulations", "journals": "J Nucl Med; Eur J Nucl Med Mol Imaging; Clin Nucl Med; Nucl Med Commun; Semin Nucl Med; Q J Nucl Med Mol Imaging; Nucl Med Biol; J Nucl Cardiol; Cancer Biother Radiopharm; Mol Imaging Biol"}]},
    {"label": "Obstetrics and Gynecology", "subspecialties": [
        {"label": "General/Core", "topics": "Prenatal Care & Screening; Labor Management & Delivery; Obstetric Hemorrhage; Hypertensive Disorders of Pregnancy; Abnormal Uterine Bleeding; Contraception & Family Planning; Cervical Cancer Screening/Colposcopy; Menopause Management; Pelvic Pain & Endometriosis; Early Pregnancy Loss; Benign Gynecologic Surgery; Infertility Evaluation; Vulvar Disease; STI Management; Adnexal Mass Evaluation", "journals": "Hum Reprod Update; Am J Obstet Gynecol; Obstet Gynecol; Hum Reprod; Ultrasound Obstet Gynecol; BJOG; Fertil Steril; Gynecol Oncol; Contraception; Menopause"},
        {"label": "Maternal-Fetal Medicine", "topics": "Preterm Labor Management; Multiple Gestation Care; Diabetes in Pregnancy; Fetal Growth Restriction; Placenta Accreta Spectrum; Severe Preeclampsia/Eclampsia; Prenatal Genetic Diagnosis; Maternal Cardiac Disease; Infectious Diseases in Pregnancy; Alloimmunization; Fetal Anomalies Management; Thromboembolism in Pregnancy; Critical Care Obstetrics; Obesity in Pregnancy; Fetal Surgery/Therapy", "journals": "Am J Obstet Gynecol MFM; J Matern Fetal Neonatal Med; Prenat Diagn; Fetal Diagn Ther; Semin Perinatol; Placenta; Pregnancy Hypertens; BMC Pregnancy Childbirth; Paediatr Perinat Epidemiol; J Perinatol"},
        {"label": "Reproductive Endocrinology", "topics": "Infertility Treatments (IVF/IUI); Polycystic Ovary Syndrome (PCOS); Recurrent Pregnancy Loss; Endometriosis & Fibroids; Primary Ovarian Insufficiency; Male Factor Infertility; Congenital Uterine Anomalies; Preservation of Fertility; Amenorrhea Evaluation; Pubertal Disorders; Menopausal Hormone Therapy; Preimplantation Genetic Testing; Gamete Donation; Reproductive Surgery; Psychosocial Aspects of Infertility", "journals": "Fertil Steril; Hum Reprod; Hum Reprod Update; J Assist Reprod Genet; Reprod Biomed Online; Mol Hum Reprod; Biol Reprod; Reprod Sci; Semin Reprod Med; J Clin Endocrinol Metab"},
        {"label": "Gynecologic Oncology", "topics": "Ovarian Cancer Surgery/Chemo; Endometrial Cancer Management; Cervical Cancer Treatment; Vulvar/Vaginal Cancers; Gestational Trophoblastic Disease; Minimally Invasive Gyn Oncology; Genetic Counseling (BRCA/Lynch); Radiation Therapy Principles; Palliative Care in Oncology; Sentinel Node Mapping; Radical Hysterectomy; Exenteration Procedures; Targeted Therapies (PARP inhibitors); Pre-invasive Disease Management; Clinical Trials", "journals": "Gynecol Oncol; Int J Gynecol Cancer; J Clin Oncol; Lancet Oncol; Gynecol Oncol Rep; Curr Opin Obstet Gynecol; Am J Obstet Gynecol; Cancer; Ann Surg Oncol; Clin Cancer Res"},
    ]},
    {"label": "Ophthalmology", "subspecialties": [{"label": "General/Core", "topics": "Cataract Surgery (Phaco); Glaucoma Management; Age-Related Macular Degeneration; Diabetic Retinopathy; Dry Eye Disease; Retinal Detachment; Uveitis Evaluation; Corneal Dystrophies & Ulcers; Neuro-Ophthalmology (Optic Nerve); Pediatric Ophthalmology (Strabismus); Oculoplastics (Eyelids/Orbit); Refractive Surgery (LASIK); Ocular Trauma; Orbital Disease; Conjunctival Disease", "journals": "Ophthalmology; JAMA Ophthalmol; Prog Retin Eye Res; Am J Ophthalmol; Br J Ophthalmol; Invest Ophthalmol Vis Sci; Retina; J Glaucoma; Cornea; J Cataract Refract Surg"}]},
    {"label": "Orthopaedic Surgery", "subspecialties": [{"label": "General/Core", "topics": "Fracture Management Principles; Total Hip Arthroplasty; Total Knee Arthroplasty; Rotator Cuff Pathology; ACL Injury & Reconstruction; Carpal Tunnel Syndrome; Spine Trauma Clearance; Lumbar Disc Herniation; Pediatric Hip Disorders; Hand Trauma/Reimplantation; Shoulder Instability; Bone Tumors; Musculoskeletal Infection; Foot & Ankle Disorders; Compartment Syndrome", "journals": "J Bone Joint Surg Am; Am J Sports Med; Bone Joint J; Clin Orthop Relat Res; Arthroscopy; J Arthroplasty; Spine; J Orthop Trauma; J Hand Surg Am; Acta Orthop"}]},
    {"label": "Otolaryngology", "subspecialties": [{"label": "General/Core", "topics": "Hearing Loss Evaluation; Otitis Media & Mastoiditis; Sinusitis & FESS; Tonsillitis & Adenoiditis; Head & Neck Cancer (Squamous); Thyroid/Parathyroid Surgery; Obstructive Sleep Apnea; Vertigo & Balance Disorders; Facial Trauma & Fractures; Voice Disorders (Laryngology); Pediatric Airway; Salivary Gland Pathology; Facial Plastic & Reconstructive; Rhinitis & Allergy; Dysphagia", "journals": "JAMA Otolaryngol Head Neck Surg; Otolaryngol Head Neck Surg; Laryngoscope; Int J Pediatr Otorhinolaryngol; Head Neck; Ear Hear; Am J Rhinol Allergy; Dysphagia; Ann Otol Rhinol Laryngol; Eur Arch Otorhinolaryngol"}]},
    {"label": "Pathology", "subspecialties": [
        {"label": "Anatomic Pathology", "topics": "Breast Pathology; Gastrointestinal Pathology; Genitourinary Pathology; Gynecologic Pathology; Pulmonary Pathology; Dermatopathology Basics; Cytopathology (Pap/FNA); Neuropathology Basics; Head & Neck Pathology; Soft Tissue/Bone Pathology; Autopsy Pathology; Intraoperative Consultation (Frozen); Immunohistochemistry; Molecular Pathology Basics; Quality Assurance", "journals": "Mod Pathol; Am J Surg Pathol; Arch Pathol Lab Med; Histopathology; Virchows Arch; Hum Pathol; Adv Anat Pathol; Am J Clin Pathol; Cancer Cytopathol; Diagn Cytopathol"},
        {"label": "Clinical Pathology", "topics": "Transfusion Medicine/Blood Banking; Clinical Microbiology; Clinical Chemistry; Hematopathology (Peripheral/Marrow); Coagulation Testing; Molecular Diagnostics; Immunology/Serology; Urinalysis & Fluids; Laboratory Management; Toxicology Screening; Cytogenetics; Point-of-Care Testing; Flow Cytometry; Histocompatibility; Informatics", "journals": "Clin Chem; Am J Clin Pathol; Transfusion; J Clin Microbiol; Arch Pathol Lab Med; Clin Chem Lab Med; J Mol Diagn; Vox Sang; Int J Lab Hematol; Ther Drug Monit"},
    ]},
    {"label": "Pediatrics", "subspecialties": [
        {"label": "General/Core", "topics": "Growth & Development Assessment; Immunization Schedule; Newborn Care & Resuscitation; Acute Infections (Otitis/URI); Asthma Management; Adolescent Health Screening; Behavioral Disorders (ADHD); Nutrition & Obesity; Pediatric Dermatology; GI Disorders (Constipation/GERD); Injury Prevention; Fever of Unknown Origin; Child Abuse Recognition; Fluid & Electrolyte Management; Murmur Evaluation", "journals": "JAMA Pediatr; Pediatrics; Lancet Child Adolesc Health; J Pediatr; Arch Dis Child; Pediatr Res; J Adolesc Health; Pediatr Infect Dis J; Eur J Pediatr; Acad Pediatr"},
        {"label": "Neonatal-Perinatal Medicine", "topics": "Neonatal Resuscitation Program (NRP); Prematurity Complications (RDS/BPD); Necrotizing Enterocolitis; Neonatal Sepsis; Hyperbilirubinemia; Hypoxic-Ischemic Encephalopathy; Congenital Anomalies; Fluid/Electrolyte Balance; Nutrition (TPN/Feeding); Neonatal Abstinence Syndrome; Retinopathy of Prematurity; Persistent Pulmonary Hypertension; Intraventricular Hemorrhage; Discharge Planning; Family-Centered Care", "journals": "Pediatrics; JAMA Pediatr; J Pediatr; Arch Dis Child Fetal Neonatal Ed; Semin Fetal Neonatal Med; Neonatology; J Perinatol; Early Hum Dev; Am J Perinatol; Clin Perinatol"},
        {"label": "Pediatric Cardiology", "topics": "Congenital Heart Disease (Cyanotic/Acyanotic); Heart Failure in Children; Arrhythmias & Electrophysiology; Kawasaki Disease; Rheumatic Heart Disease; Cardiomyopathy; Syncope & Chest Pain; Hypertension in Children; Preventive Cardiology (Lipids); Cardiac Catheterization; Fetal Cardiology; Adult Congenital Heart Disease; Myocarditis/Pericarditis; Pulmonary Hypertension; Post-Op Cardiac Care", "journals": "J Am Coll Cardiol; Circulation; Pediatr Cardiol; Congenit Heart Dis; Cardiol Young; Heart Rhythm; Catheter Cardiovasc Interv; J Thorac Cardiovasc Surg; Ann Thorac Surg; Eur Heart J"},
        {"label": "Pediatric Critical Care", "topics": "Respiratory Failure (Ventilation); Shock (Septic/Cardiogenic); Traumatic Brain Injury; Status Epilepticus; Diabetic Ketoacidosis; Fluid & Electrolyte Emergencies; Sedation & Analgesia; ECMO Management; Multiple Organ Dysfunction; Renal Replacement Therapy; Post-Op Surgical Care; Toxicology/Overdose; Child Abuse (Non-accidental Trauma); Transport Medicine; End-of-Life Care; Mechanical Circulatory Support and ECMO", "journals": "Pediatr Crit Care Med; Crit Care Med; Intensive Care Med; Am J Respir Crit Care Med; Chest; Resuscitation; J Trauma Acute Care Surg; Shock; Pediatr Emerg Care; J Pediatr Intensive Care; ASAIO J"},
    ]},
    {"label": "Physical Medicine and Rehabilitation", "subspecialties": [{"label": "General/Core", "topics": "Traumatic Brain Injury Rehab; Spinal Cord Injury Management; Stroke Rehabilitation; Amputation & Prosthetics; Musculoskeletal Pain; Gait Analysis & Orthotics; Spasticity Management; EMG/NCS Electrodiagnosis; Pediatric Rehabilitation (CP); Cardiopulmonary Rehab; Sports Medicine; Industrial/Occupational Rehab; Chronic Pain Management; Wheelchair/Equipment Prescription; Disability Evaluation", "journals": "Arch Phys Med Rehabil; Am J Phys Med Rehabil; PM&R; J Rehabil Med; Clin Rehabil; Neurorehabil Neural Repair; Spinal Cord; Brain Inj; Prosthet Orthot Int; Musculoskelet Sci Pract"}]},
    {"label": "Plastic Surgery", "subspecialties": [{"label": "General/Core", "topics": "Wound Healing & Repair; Skin Grafts & Flaps; Burn Reconstruction; Hand Surgery (Trauma/Congenital); Breast Reconstruction; Aesthetic Surgery (Face/Body); Craniofacial Surgery; Microsurgery Principles; Head & Neck Reconstruction; Lower Extremity Reconstruction; Cleft Lip & Palate; Skin Cancer Reconstruction; Peripheral Nerve Surgery; Vascular Malformations; Soft Tissue Sarcoma", "journals": "Plast Reconstr Surg; J Plast Reconstr Aesthet Surg; Aesthet Surg J; Ann Plast Surg; Clin Plast Surg; Burns; Microsurgery; J Hand Surg Am; Cleft Palate Craniofac J; JAMA Facial Plast Surg"}]},
    {"label": "Preventive Medicine", "subspecialties": [
        {"label": "General/Core", "topics": "Clinical Preventive Services (USPSTF/ACIP); Cancer Screening Program Design; Immunization Strategy and Coverage; Cardiometabolic Risk Reduction; Tobacco and Substance Risk Reduction; Obesity and Lifestyle Counseling; Travel and Global Health Prevention; Environmental Exposure Prevention; Occupational Risk Prevention; Injury and Violence Prevention; Maternal-Child Prevention Programs; Population Health Surveillance; Health Equity and Social Determinants; Disaster Preparedness and Public Health Emergency Response; Implementation of Prevention Guidelines", "journals": "Am J Prev Med; Prev Med; Lancet Public Health; Am J Public Health; Ann Fam Med; Public Health Rep; Int J Epidemiol; J Public Health; BMC Public Health; BMJ Public Health"},
        {"label": "Aerospace Medicine", "topics": "Hypoxia & Barotrauma; Acceleration Physiology; Spatial Disorientation; Pilot Medical Certification; Spaceflight Physiology; Travel Medicine; Aircrew Health/Safety; Accident Investigation; Radiation in Flight; Jet Lag/Fatigue; Decompression Sickness; Ejection Injuries; Airline Medical Emergencies; Oxygen Systems; Hyperbaric Chambers", "journals": "Aerosp Med Hum Perform; J Travel Med; High Alt Med Biol; Undersea Hyperb Med; Prehosp Disaster Med; Occup Environ Med; Am J Prev Med; Mil Med; Wilderness Environ Med; Int Marit Health"},
        {"label": "Occupational and Environmental Medicine", "topics": "Work-Related Injuries; Occupational Toxicology; Ergonomics & MSK Disorders; Fitness for Duty Exams; Environmental Hazards; Workers' Compensation; Hearing Conservation; Respiratory Protection; Disability Management; Disaster Preparedness; Commercial Driver Exams; Substance Abuse in Workplace; Industrial Hygiene; Epidemiology of Work; Travel Health", "journals": "Occup Environ Med; Am J Ind Med; J Occup Environ Med; Scand J Work Environ Health; Int Arch Occup Environ Health; Ann Work Expo Health; Ind Health; Occup Med; Saf Health Work; Work"},
        {"label": "Public Health and General Preventive Medicine", "topics": "Epidemiology Principles; Biostatistics; Disease Surveillance; Environmental Health; Health Policy & Management; Infectious Disease Control; Chronic Disease Prevention; Immunization Programs; Health Promotion; Maternal-Child Health; Global Health; Public Health Ethics; Disaster Response; Social Determinants; Clinical Preventive Services", "journals": "Am J Prev Med; Prev Med; Lancet Public Health; Am J Public Health; Annu Rev Public Health; BMC Public Health; Int J Epidemiol; Bull World Health Organ; Public Health Rep; J Public Health"},
    ]},
    {"label": "Psychiatry", "subspecialties": [
        {"label": "General/Core", "topics": "Major Depressive Disorder; Schizophrenia Spectrum; Bipolar Disorders; Anxiety Disorders; Substance Use Disorders; PTSD & Trauma; Suicide Risk Assessment; Personality Disorders; OCD; Delirium Management; Eating Disorders; Somatic Symptom Disorders; Emergency Psychiatry; Psychopharmacology; Child Psychiatry Basics", "journals": "World Psychiatry; JAMA Psychiatry; Am J Psychiatry; Lancet Psychiatry; Mol Psychiatry; Biol Psychiatry; Psychol Med; J Clin Psychiatry; Br J Psychiatry; Schizophr Bull"},
        {"label": "Addiction Psychiatry", "topics": "Alcohol Use Disorder; Opioid Use Disorder (MAT); Stimulant Use Disorders; Withdrawal Management; Dual Diagnosis; Behavioral Addictions; Toxicology Testing; Motivation Enhancement; Relapse Prevention; Harm Reduction; Pharmacology of Addiction; Neurobiology of Addiction; Public Health & Policy; Pain & Addiction; Adolescent Substance Use", "journals": "Addiction; Am J Addict; J Addict Med; Drug Alcohol Depend; Addict Behav; Int J Drug Policy; Eur Addict Res; Alcohol Clin Exp Res; J Subst Abuse Treat; Nicotine Tob Res"},
    ]},
    {"label": "Radiology", "subspecialties": [{"label": "Diagnostic Radiology", "topics": "Stroke Imaging (CT/MRI); Chest Imaging (Pneumonia/Nodules); Abdominal Trauma; Acute Abdomen Imaging; Breast Imaging (BI-RADS); Musculoskeletal MRI; Neuroradiology (Tumor/Stroke); Vascular Ultrasound; Liver Mass Characterization; Genitourinary Imaging; Pediatric Radiology Basics; Nuclear Medicine Basics; Interventional Procedures (Biopsy); Head & Neck Imaging; Radiation Safety/Physics", "journals": "Radiology; JACC Cardiovasc Imaging; IEEE Trans Med Imaging; Eur Radiol; AJR Am J Roentgenol; J Nucl Med; Radiographics; Invest Radiol; J Magn Reson Imaging; Acad Radiol"}]},
    {"label": "Surgery (General)", "subspecialties": [
        {"label": "General/Core", "topics": "Acute Abdomen; Hernia Repair; Trauma Surgery (ATLS); Colorectal Cancer Resection; Breast Cancer Surgery; Bowel Obstruction; Gallbladder/Biliary Surgery; Skin/Soft Tissue Infections; Thyroid/Parathyroid Surgery; Foregut Surgery (GERD); Vascular Access; Surgical Critical Care; Pancreatic Surgery; Diverticulitis Management; Bariatric Surgery", "journals": "Ann Surg; JAMA Surg; Br J Surg; J Am Coll Surg; Surgery; World J Surg; Surg Endosc; J Gastrointest Surg; J Trauma Acute Care Surg; Am J Transplant"},
        {"label": "Pediatric Surgery", "topics": "Congenital Diaphragmatic Hernia; Esophageal Atresia/TEF; Gastroschisis/Omphalocele; Hirschsprung Disease; Anorectal Malformations; Pyloric Stenosis; Intussusception; Necrotizing Enterocolitis; Pediatric Tumors (Wilms/Neuroblastoma); Biliary Atresia; Inguinal Hernia/Hydrocele; Appendicitis in Children; Trauma in Children; ECMO; Short Bowel Syndrome", "journals": "J Pediatr Surg; Pediatr Surg Int; Eur J Pediatr Surg; Semin Pediatr Surg; J Laparoendosc Adv Surg Tech A; J Trauma Acute Care Surg; Pediatrics; JAMA Surg; Ann Surg; Surgery"},
        {"label": "Vascular Surgery", "topics": "Abdominal Aortic Aneurysm (Open/EVAR); Carotid Endarterectomy & Stenting; Peripheral Artery Disease (Bypass/Endo); Critical Limb Ischemia; Venous Insufficiency & Ablation; Deep Vein Thrombosis & Thrombolysis; Dialysis Access Creation; Thoracic Outlet Syndrome; Mesenteric Ischemia; Renal Artery Stenosis; Aortic Dissection (Vascular management); Vascular Trauma; Diabetic Foot Management; Amputation Levels; Vasculitis", "journals": "J Vasc Surg; Eur J Vasc Endovasc Surg; Ann Vasc Surg; J Endovasc Ther; J Vasc Surg Venous Lymphat Disord; J Vasc Interv Radiol; Vasc Med; Semin Vasc Surg; Vascular; Angiology"},
        {"label": "Trauma Surgery", "topics": "ATLS Protocols; Damage Control Surgery; Massive Transfusion Protocols; REBOA; Penetrating Neck Injury; Thoracic Trauma (Thoracotomy); Abdominal Solid Organ Injury (Liver/Spleen); Pelvic Fracture Stabilization; Traumatic Brain Injury (Surgical mgt); Compartment Syndrome; Burns & Inhalation Injury; Necrotizing Soft Tissue Infections; Rib Fracture Fixation; FAST Exam; Critical Care of the Trauma Patient", "journals": "J Trauma Acute Care Surg; Trauma Surg Acute Care Open; Injury; Scand J Trauma Resusc Emerg Med; World J Emerg Surg; Eur J Trauma Emerg Surg; J Surg Res; Am J Surg; Burns; Shock"},
        {"label": "Hepatobiliary Surgery", "topics": "Pancreaticoduodenectomy (Whipple); Distal Pancreatectomy; Major Liver Resection; Hilar Cholangiocarcinoma (Klatskin); Gallbladder Cancer Resection; Complex Biliary Strictures; Hepatocellular Carcinoma Management; Liver Metastasis Resection; Laparoscopic/Robotic HPB Surgery; Acute/Chronic Pancreatitis Surgery; Liver Transplantation Techniques; Portal Hypertension Shunts; Hepatic Abscess/Cyst Management; Bile Duct Injury Repair; Intraoperative Ultrasound HPB", "journals": "Ann Hepato-Biliary-Pancreat Surg; J Gastrointest Surg; Hepatobiliary Surg Nutr; Surgery; Ann Surg Oncol; Liver Transpl; Pancreatology; World J Surg; Langenbecks Arch Surg"},
    ]},
    {"label": "Thoracic Surgery", "subspecialties": [{"label": "General/Core", "topics": "Lung Cancer (Lobectomy); Esophageal Cancer; Coronary Artery Bypass (CABG); Aortic Valve Replacement; Mitral Valve Repair; Aortic Aneurysm/Dissection; Mediastinal Tumors; Pleural Effusion/Empyema; Pneumothorax; Chest Wall Deformities; Heart/Lung Transplantation; Congenital Heart Surgery; Mechanical Circulatory Support; Arrhythmia Surgery; Critical Care Management", "journals": "Ann Thorac Surg; J Thorac Cardiovasc Surg; Eur J Cardiothorac Surg; J Heart Lung Transplant; Chest; Semin Thorac Cardiovasc Surg; Oper Tech Thorac Cardiovasc Surg; Thorax; Interact Cardiovasc Thorac Surg; Innovations"}]},
    {"label": "Urology", "subspecialties": [{"label": "General/Core", "topics": "Prostate Cancer; Nephrolithiasis (Stones); BPH & LUTS; Bladder Cancer; Renal Mass Evaluation; Erectile Dysfunction; Urinary Incontinence; Pediatric Urology Basics; Testicular Cancer; Genitourinary Trauma; Urinary Tract Infections; Male Infertility; Scrotal Pathology; Adrenal Disorders; Urethral Stricture Disease", "journals": "Eur Urol; J Urol; Nat Rev Urol; BJU Int; Urology; Prostate Cancer Prostatic Dis; World J Urol; Neurourol Urodyn; J Sex Med; Urol Oncol"}]},
    {"label": "AI in Medicine", "subspecialties": [
        {"label": "General/Core", "topics": "Clinical Decision Support; Predictive Risk Modeling; Generative AI for Documentation; Natural Language Processing on EHR Data; Imaging and Signal AI; Ambient Scribing; Workflow Automation; Multimodal Foundation Models; Dataset Shift and Model Drift; Bias, Fairness, and Health Equity; Explainability and Transparency; Human-AI Teaming; Prospective Clinical Validation; Privacy, Security, and Cybersecurity; Governance, Regulation, and Lifecycle Monitoring", "journals": "Lancet Digit Health; npj Digit Med; JAMIA; J Biomed Inform; Artif Intell Med; NEJM AI; BMJ Health Care Inform; JAMIA Open; Nat Med; PLOS Digit Health"},
        {"label": "Clinical Decision Support and Predictive Analytics", "topics": "Sepsis and Deterioration Prediction; AKI and Readmission Models; Diagnostic Support Tools; Precision Risk Stratification; Time-Series and Streaming Data Models; External Validation and Transportability; Calibration and Threshold Setting; Silent-Mode Workflow Evaluation; Alert Fatigue and Cognitive Load; Causal Inference versus Prediction; Real-World Performance Monitoring; Fairness Across Subgroups; EHR Data Quality and Missingness; Implementation in Clinical Operations; Prospective Impact Trials", "journals": "JAMIA; Lancet Digit Health; npj Digit Med; J Biomed Inform; Artif Intell Med; BMJ Health Care Inform; NEJM AI; Nat Med; JAMIA Open; PLOS Digit Health"},
        {"label": "Generative AI and Clinical Documentation", "topics": "Ambient Scribing; Note Summarization; Chart Review Synthesis; Inbox and Patient Message Drafting; Prior Authorization and Utilization Management Support; Coding and Billing Assistance; Retrieval Augmented Generation; Hallucination Detection and Mitigation; PHI Protection and Secure Deployment; Prompt Design and Evaluation; Human Review and Accountability; Multilingual Documentation; Handoff and Discharge Summary Support; Education and Coaching with LLMs; Measuring Burden Reduction and Safety", "journals": "NEJM AI; JAMIA; Lancet Digit Health; npj Digit Med; BMJ Health Care Inform; J Biomed Inform; Artif Intell Med; JAMIA Open; PLOS Digit Health; Nat Med"},
        {"label": "Imaging, Signals, and Multimodal AI", "topics": "Radiology Triage and Detection Models; Digital Pathology AI; ECG and EEG Interpretation Models; Echocardiography AI; Dermatology and Wound Imaging; Endoscopy and Procedural AI; Multimodal Fusion of Text, Image, and Signal Data; Foundation Models; Labeling and Annotation Strategy; Cross-Site Generalizability; False Positives and Automation Bias; Human-in-the-Loop Review; Federated and Privacy-Preserving Learning; Device Integration as SaMD; Prospective Clinical Utility Studies", "journals": "Radiology; Med Image Anal; IEEE Trans Med Imaging; Eur Radiol; J Digital Imaging; Lancet Digit Health; npj Digit Med; Nat Med; J Biomed Inform; Artif Intell Med"},
        {"label": "AI Governance, Safety, and Evaluation", "topics": "Bias and Fairness Audits; Good Machine Learning Practice; Total Product Lifecycle Management; FDA Regulatory Pathways; Procurement and Vendor Due Diligence; Model Documentation and Transparency; Post-Deployment Surveillance; Human Factors and Usability Testing; Incident Response and Escalation; Data Provenance and Consent; Reporting Standards (CONSORT-AI/SPIRIT-AI/TRIPOD-AI); Security and Adversarial Risk; Equity Impact Assessment; Reimbursement and Value Analysis; Organizational Governance Structures", "journals": "JAMIA; Lancet Digit Health; npj Digit Med; BMJ Qual Saf; J Biomed Inform; Artif Intell Med; NEJM AI; BMJ Health Care Inform; Nat Med; PLOS Digit Health"},
    ]},
    {"label": "Longevity", "subspecialties": [
        {"label": "General/Core", "topics": "Healthspan versus Lifespan; Frailty Assessment; Sarcopenia and Mobility; Polypharmacy and Deprescribing; Exercise and Resistance Training; Nutrition and Protein Adequacy; Sleep and Circadian Health; Cognitive Health Maintenance; Falls Prevention; Bone Health and Fracture Prevention; Cardiometabolic Risk Reduction in Aging; Social Connection and Loneliness; Vaccination and Infection Resilience; Multimorbidity Optimization; Advance Care Planning and Functional Trajectory Planning", "journals": "Lancet Healthy Longev; Age Ageing; J Am Geriatr Soc; J Gerontol A Biol Sci Med Sci; Geroscience; Ageing Res Rev; Nature Aging; Aging Cell; J Am Med Dir Assoc; BMC Geriatr"},
        {"label": "Geroscience and Aging Biology", "topics": "Hallmarks of Aging; Cellular Senescence; Inflammaging; Epigenetic Clocks; Mitochondrial Dysfunction; Proteostasis and Autophagy; NAD and Metabolic Pathways; Immune Aging; Stem Cell Exhaustion; Vascular Aging; Resilience and Biological Reserve; Biomarkers of Biological Age; Translational Gerotherapeutic Trials; Mechanisms Linking Aging and Chronic Disease; Ethical and Clinical Limits of Biomarker Use", "journals": "Nature Aging; Aging Cell; Geroscience; Ageing Res Rev; J Gerontol A Biol Sci Med Sci; Cell Metab; Nat Med; Sci Transl Med; Mech Ageing Dev; Lancet Healthy Longev"},
        {"label": "Healthy Longevity and Prevention", "topics": "Cardiovascular Prevention in Older Adults; Diabetes and Obesity Prevention; Cancer Screening Individualization; Vaccination in Older Adults; Hearing and Vision Preservation; Sleep Optimization; Mediterranean and Plant-Forward Nutrition; Exercise Prescription for Healthspan; Cognitive Reserve and Dementia Risk Reduction; Menopause and Healthy Aging; Social Isolation and Loneliness Mitigation; Medication Optimization; Health Equity in Aging; Community-Based Aging Interventions; Preventive Geriatrics and Functional Screening", "journals": "Lancet Healthy Longev; J Am Geriatr Soc; Age Ageing; JAMA Intern Med; Ann Intern Med; BMJ; N Engl J Med; Circulation; Diabetes Care; BMC Med"},
        {"label": "Frailty, Sarcopenia, and Functional Aging", "topics": "Frailty Phenotypes and Indices; Sarcopenia Diagnosis; Gait Speed and Mobility Metrics; Falls and Balance Disorders; Resistance Training Interventions; Protein and Anabolic Nutrition; Osteoporosis and Fracture Prevention; Post-Acute Rehabilitation; Wearable Monitoring of Function; Disability Trajectories; Orthostatic Hypotension and Functional Symptoms; Continence and Functional Independence; Sensory Impairment and Function; Prehabilitation for Surgery and Illness; Integrated Function-Focused Care", "journals": "J Cachexia Sarcopenia Muscle; J Am Med Dir Assoc; Age Ageing; J Gerontol A Biol Sci Med Sci; J Am Geriatr Soc; Arch Gerontol Geriatr; Clin Interv Aging; Osteoporos Int; J Frailty Aging; BMC Geriatr"},
    ]},
    {"label": "Physical and Mental Wellness", "subspecialties": [
        {"label": "General/Core", "topics": "Lifestyle Medicine Pillars; Behavior Change and Motivational Interviewing; Exercise Prescription; Nutrition Optimization; Restorative Sleep; Stress Management; Social Connection and Community; Risky Substance Avoidance; Obesity and Cardiometabolic Wellness; Burnout and Clinician Well-Being; Mind-Body Therapies; Preventive Mental Health; Wearables and Self-Monitoring; Health Coaching and Shared Goals; Workplace and Organizational Wellness", "journals": "Am J Lifestyle Med; Lifestyle Med; Ann Behav Med; Health Psychol; Psychosom Med; J Behav Med; Sleep Health; Prev Med; BMJ Ment Health; Lancet Psychiatry"},
        {"label": "Physical Wellness", "topics": "Exercise Prescription for Prevention and Recovery; Resistance and Aerobic Training; Nutrition and Metabolic Health; Obesity and Weight Management; Sleep Optimization; Recovery and Fatigue Management; Musculoskeletal Injury Prevention; Mobility and Functional Fitness; Cardiovascular Fitness and Risk Reduction; Bone Health and Osteoporosis Prevention; Menopause and Exercise; Wearables and Activity Tracking; Tobacco and Alcohol Risk Reduction; Chronic Disease Reversal through Lifestyle Change; Workplace Ergonomics and Physical Resilience", "journals": "Br J Sports Med; Med Sci Sports Exerc; Sports Med; J Orthop Sports Phys Ther; Obesity; Am J Lifestyle Med; Lifestyle Med; Sleep Health; Circulation; Diabetes Care"},
        {"label": "Mental Wellness", "topics": "Stress and Allostatic Load; Resilience Training; Burnout and Moral Injury; Mindfulness-Based Interventions; Sleep and Mental Health; Anxiety Prevention and Early Intervention; Depression Prevention; Substance Risk Reduction; Social Connectedness and Loneliness; Trauma-Informed Care; Digital Mental Health Tools; Workplace Mental Health; Suicide Prevention and Crisis Planning; Positive Psychology and Meaning; Integrated Behavioral Health in Chronic Disease", "journals": "Lancet Psychiatry; JAMA Psychiatry; Ann Behav Med; Health Psychol; Psychosom Med; BMJ Ment Health; J Behav Med; Gen Hosp Psychiatry; Stress Health; Am J Lifestyle Med"},
    ]},
    {"label": "Nursing Research", "subspecialties": [
        {"label": "General/Core", "topics": "Symptom Science and Patient Experience; Care Delivery Models; Evidence-Based Practice; Quality and Patient Safety; Health Equity and Social Determinants of Health; Workforce and Staffing; Education and Competency Development; Self-Management and Caregiver Research; Community and Population Health; Implementation Science; Digital Health and Informatics; Palliative and Supportive Care; Measurement and Instrument Development; Mixed Methods and Pragmatic Trials; Policy Translation and Systems Change", "journals": "Int J Nurs Stud; Nursing Research; J Nurs Scholarsh; J Adv Nurs; Res Nurs Health; Worldviews Evid Based Nurs; J Clin Nurs; Nurs Outlook; J Prof Nurs; Int Nurs Rev"},
        {"label": "Clinical Nursing Research", "topics": "Symptom Management; Chronic Disease Self-Management; Care Transitions; Patient and Family Education; Wound and Skin Care; Infection Prevention and Nursing-Sensitive Outcomes; Palliative and Supportive Care; Critical Care Nursing Interventions; Oncology Nursing Care Models; Maternal-Child and Family-Centered Care; Mental Health Nursing Interventions; Telehealth and Remote Monitoring; Patient-Reported Outcomes; Implementation of Evidence-Based Nursing Interventions; Pragmatic Trials of Nursing Care", "journals": "Clinical Nursing Research; Nursing Research; Int J Nurs Stud; J Clin Nurs; J Adv Nurs; Res Nurs Health; J Nurs Scholarsh; Worldviews Evid Based Nurs; Nurs Outlook; BMC Nurs"},
        {"label": "Nursing Education Research", "topics": "Competency-Based Education; Simulation and Debriefing; Clinical Reasoning and Judgment; Assessment and Evaluation Methods; Curriculum Design; Faculty Development; Preceptor and Clinical Placement Models; Transition-to-Practice and Residency Programs; Interprofessional Education; Online and Hybrid Learning; AI-Supported Learning Tools; Diversity, Equity, and Inclusion in Education; Learner Well-Being; Doctoral and Advanced Practice Education; Regulatory and Licensure Readiness", "journals": "Nurse Educ Today; J Prof Nurs; J Nurs Educ; Nurse Educ; Nurse Educ Pract; Clin Simul Nurs; Int J Nurs Educ Scholarsh; Teach Learn Nurs; J Contin Educ Nurs; BMC Med Educ"},
        {"label": "Nursing Leadership and Administration Research", "topics": "Staffing and Skill Mix; Workload, Burnout, and Retention; Nurse Manager Effectiveness; Leadership Styles and Team Climate; Shared Governance; Healthy Work Environments; Workplace Violence and Safety Culture; Resource Allocation and Budgeting; Succession Planning; Innovation and Change Management; Workforce Analytics; Diversity and Inclusion in Leadership; Magnet and Professional Practice Models; Technology Adoption by Nursing Teams; Leadership Development and Coaching", "journals": "J Nurs Manag; JONA; Nurs Outlook; Int J Nurs Stud; J Nurs Care Qual; J Nurs Scholarsh; J Clin Nurs; Health Care Manage Rev; BMJ Qual Saf; Worldviews Evid Based Nurs"},
        {"label": "Health Systems, Quality, and Outcomes Research", "topics": "Nurse Staffing and Patient Outcomes; Patient Safety and Harm Reduction; Quality Measurement and Benchmarking; Implementation Science and De-implementation; Value-Based Care; Care Coordination and Transitions; Health Services Research Methods; Patient-Reported Outcomes and Experience; Equity and Disparities in Care Delivery; Digital Quality Metrics and Data Infrastructure; Population Health Management; Cost-Effectiveness and Resource Utilization; Workforce Policy and Regulation; Improvement Science; Integrated and Community-Linked Models of Care", "journals": "Medical Care; Health Serv Res; BMJ Qual Saf; J Nurs Care Qual; Worldviews Evid Based Nurs; Nurs Outlook; Int J Nurs Stud; J Adv Nurs; J Nurs Scholarsh; Implement Sci"},
    ]},
]

# Legacy ID mappings — maps old IDs to current specialties for backward compat
LEGACY_ID_MAP = {
    # Old combined specialty
    "allergy_immunology_pathology_genetics": "allergy_and_immunology",
    # Old "oncology" shorthand
    "oncology": "internal_medicine",
    # Old subspecialty IDs
    "general_cardiology": "cardiology_general_cardiology",
    "internal_medicine_cardiovascular_disease": "cardiology_general_cardiology",
    "internal_medicine_geriatric_medicine": "longevity_general_core",
    "internal_medicine_oncology": "internal_medicine_medical_oncology",
}

def build_config():
    specialties = []
    
    for spec_data in NEW_TAXONOMY:
        spec_label = spec_data["label"]
        spec_id = make_id(spec_label)
        
        subspecialties = []
        for sub_data in spec_data["subspecialties"]:
            sub_label = sub_data["label"]
            sub_id = f"{spec_id}_{make_id(sub_label)}"
            
            topics = [t.strip() for t in sub_data["topics"].split(";") if t.strip()]
            journals = [j.strip() for j in sub_data["journals"].split(";") if j.strip()]
            
            subspecialties.append({
                "id": sub_id,
                "label": sub_label,
                "topics": topics,
                "top_journals": journals,
            })
        
        specialties.append({
            "id": spec_id,
            "label": spec_label,
            "subspecialties": subspecialties,
        })
    
    # Add legacy combined specialty (deprecated, hidden from new onboarding)
    specialties.append({
        "id": "allergy_immunology_pathology_genetics",
        "label": "Allergy, Immunology, Pathology & Medical Genetics",
        "deprecated": True,
        "maps_to": ["allergy_and_immunology", "pathology", "medical_genetics"],
        "subspecialties": [
            {"id": "allergy_immunology_pathology_genetics_general_core", "label": "General/Core", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "allergy_and_immunology_general_core"},
            {"id": "allergy_immunology_pathology_genetics_allergy_and_immunology_and_immunology_general_core", "label": "Allergy and Immunology", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "allergy_and_immunology_general_core"},
            {"id": "allergy_immunology_pathology_genetics_pathology_anatomic_pathology", "label": "Pathology - Anatomic Pathology", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "pathology_anatomic_pathology"},
            {"id": "allergy_immunology_pathology_genetics_pathology_clinical_pathology", "label": "Pathology - Clinical Pathology", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "pathology_clinical_pathology"},
            {"id": "allergy_immunology_pathology_genetics_medical_genetics_genetics_general_core", "label": "Medical Genetics", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "medical_genetics_general_core"},
        ],
    })
    
    # Add legacy surgery_general with deprecated surgical subspecialties
    # Keep the main surgery_general entry as the active "Surgery (General)"
    # But add deprecated subspecialty aliases for old IDs
    for spec in specialties:
        if spec["id"] == "surgery_general":
            # Add deprecated aliases for subspecialties that became standalone
            spec["subspecialties"].extend([
                {"id": "surgery_thoracic_surgery", "label": "Thoracic Surgery", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "thoracic_surgery_general_core"},
                {"id": "surgery_urology", "label": "Urology", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "urology_general_core"},
                {"id": "surgery_plastic_surgery", "label": "Plastic Surgery", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "plastic_surgery_general_core"},
                {"id": "surgery_colon_and_rectal_surgery", "label": "Colon and Rectal Surgery", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "colon_and_rectal_surgery_general_core"},
                {"id": "surgery_ophthalmology", "label": "Ophthalmology", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "ophthalmology_general_core"},
                {"id": "surgery_orthopedic_surgery", "label": "Orthopaedic Surgery", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "orthopaedic_surgery_general_core"},
                {"id": "surgery_otolaryngology", "label": "Otolaryngology", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "otolaryngology_general_core"},
                {"id": "surgery_general_surgical_critical_care", "label": "Surgical Critical Care", "topics": [], "top_journals": [], "deprecated": True},
                {"id": "surgery_general_surgical_oncology", "label": "Surgical Oncology", "topics": [], "top_journals": [], "deprecated": True},
            ])
            break
    
    # Also keep legacy internal medicine subspecialties as deprecated aliases
    for spec in specialties:
        if spec["id"] == "internal_medicine":
            spec["subspecialties"].extend([
                {"id": "internal_medicine_cardiovascular_disease", "label": "Cardiovascular Disease", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "cardiology_general_cardiology"},
                {"id": "internal_medicine_geriatric_medicine", "label": "Geriatric Medicine", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "longevity_general_core"},
                {"id": "internal_medicine_endocrinology", "label": "Endocrinology", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "internal_medicine_endocrinology_diabetes_and_metabolism"},
                {"id": "internal_medicine_oncology", "label": "Oncology", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "internal_medicine_medical_oncology"},
            ])
            break
    
    # Keep legacy cardiology subspecialty IDs
    for spec in specialties:
        if spec["id"] == "cardiology":
            # Add the old "general_core" as deprecated alias
            spec["subspecialties"].insert(0, {
                "id": "cardiology_general_core",
                "label": "General/Core",
                "topics": [],
                "top_journals": [],
                "deprecated": True,
                "maps_to": "cardiology_general_cardiology",
            })
            break
    
    # Legacy OB/GYN subspecialties
    for spec in specialties:
        if spec["id"] == "obstetrics_and_gynecology":
            spec["subspecialties"].extend([
                {"id": "obstetrics_and_gynecology_general_obstetrics", "label": "General Obstetrics", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "obstetrics_and_gynecology_general_core"},
                {"id": "obstetrics_and_gynecology_general_gynecology", "label": "General Gynecology", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "obstetrics_and_gynecology_general_core"},
            ])
            break
    
    # Legacy dermatology subspecialty
    for spec in specialties:
        if spec["id"] == "dermatology":
            spec["subspecialties"].append({
                "id": "dermatology_pediatric_dermatology",
                "label": "Pediatric Dermatology",
                "topics": [],
                "top_journals": [],
                "deprecated": True,
            })
            break
    
    # Legacy emergency medicine subspecialty
    for spec in specialties:
        if spec["id"] == "emergency_medicine":
            spec["subspecialties"].append({
                "id": "emergency_medicine_pediatric_emergency_medicine",
                "label": "Pediatric Emergency Medicine",
                "topics": [],
                "top_journals": [],
                "deprecated": True,
            })
            break
    
    # Legacy psychiatry subspecialties
    for spec in specialties:
        if spec["id"] == "psychiatry":
            spec["subspecialties"].extend([
                {"id": "psychiatry_general_psychiatry", "label": "General Psychiatry", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "psychiatry_general_core"},
                {"id": "psychiatry_child_and_adolescent_psychiatry", "label": "Child and Adolescent Psychiatry", "topics": [], "top_journals": [], "deprecated": True},
            ])
            break
    
    # Legacy radiology subspecialty
    for spec in specialties:
        if spec["id"] == "radiology":
            spec["subspecialties"].extend([
                {"id": "radiology_general_core", "label": "General/Core", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "radiology_diagnostic_radiology"},
                {"id": "radiology_nuclear_medicine", "label": "Nuclear Medicine", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "nuclear_medicine_general_core"},
            ])
            break
    
    # Legacy pediatrics subspecialties
    for spec in specialties:
        if spec["id"] == "pediatrics":
            spec["subspecialties"].extend([
                {"id": "pediatrics_general_pediatrics", "label": "General Pediatrics", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "pediatrics_general_core"},
                {"id": "pediatrics_pediatric_critical_care_medicine", "label": "Pediatric Critical Care Medicine", "topics": [], "top_journals": [], "deprecated": True, "maps_to": "pediatrics_pediatric_critical_care"},
            ])
            break
    
    config = {
        "specialties": specialties,
        "legacy_id_map": LEGACY_ID_MAP,
        "version": "2.0.0",
        "updated_at": "2026-03-28",
    }
    
    return config

if __name__ == "__main__":
    config = build_config()
    
    # Stats
    active = [s for s in config["specialties"] if not s.get("deprecated")]
    deprecated = [s for s in config["specialties"] if s.get("deprecated")]
    total_subs = sum(len(s.get("subspecialties", [])) for s in config["specialties"])
    active_subs = sum(len([sub for sub in s.get("subspecialties", []) if not sub.get("deprecated")]) for s in config["specialties"])
    
    print(f"Active specialties: {len(active)}")
    print(f"Deprecated specialties: {len(deprecated)}")
    print(f"Total subspecialties: {total_subs}")
    print(f"Active subspecialties: {active_subs}")
    
    with open("/app/backend/config/specialty_config.json", "w") as f:
        json.dump(config, f, indent=2)
    
    print("\nConfig written to /app/backend/config/specialty_config.json")
